#%RAML 1.0 Trait
description: Headers used for tracking the request through the process.

headers:
  correlationId:
    displayName: Correlation Id
    description: An identifier used for tracking the request through the process.
    type: string
    required: false